//
//  SnapshotTests.swift
//  SiteNoteUITests
//
//  Fastlane Snapshot integration. Captures the 5 key screens for App Store screenshots.
//
//  Setup (one-time):
//   1. In Xcode: Editor → Add Target → iOS UI Testing Bundle (name: SiteNoteUITests)
//   2. Drag this file into the new target
//   3. Drag fastlane/SnapshotHelper.swift (generated by `fastlane snapshot init`) into the same target
//
//  Then from the repo root:  fastlane snapshot
//

import XCTest

final class SnapshotTests: XCTestCase {

    override func setUpWithError() throws {
        continueAfterFailure = false
        let app = XCUIApplication()
        setupSnapshot(app)
        app.launchArguments += ["-UITestingScreenshots", "YES"]
        app.launch()
    }

    func testCaptureKeyScreens() throws {
        let app = XCUIApplication()

        // Screen 1 — Onboarding welcome
        // -UITestingScreenshots flag forces onboarding to surface; if it's already dismissed,
        // the test reopens it via Settings.
        snapshot("01_Onboarding_Welcome")

        // Tap through onboarding to land on Record tab
        let nextButton = app.buttons["下一步"].firstMatch
        if nextButton.exists {
            // Tap "Next" up to 5 times to advance through steps
            for _ in 0..<5 {
                if nextButton.exists { nextButton.tap() }
            }
        }

        // Screen 2 — Notes list (the home Record tab)
        snapshot("02_Notes_List")

        // Screen 3 — Site filter / Calendar view (PM second tab)
        app.tabBars.buttons.element(boundBy: 1).tap()
        snapshot("03_Calendar")

        // Screen 4 — Reports tab
        app.tabBars.buttons.element(boundBy: 2).tap()
        snapshot("04_Reports")

        // Screen 5 — Settings tab
        app.tabBars.buttons.element(boundBy: 3).tap()
        snapshot("05_Settings")
    }
}
